services:
  postgres:
    image: postgres:${POSTGRES_VERSION:?required}
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    networks:
      - postgres-network
      - internal-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres-backup-local:
    image: prodrigestivill/postgres-backup-local:${POSTGRES_VERSION:?required}
    container_name: postgres-backup-local
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./.docker/postgres-backup/backups:/backups
    networks:
      - internal-network

  postgres-backup-do:
    image: eeshugerman/postgres-backup-s3:${POSTGRES_VERSION:?required}
    container_name: postgres-backup-do
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DB}
    networks:
      - internal-network

  postgres-backup-oci:
    image: eeshugerman/postgres-backup-s3:${POSTGRES_VERSION:?required}
    container_name: postgres-backup-oci
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DB}
      S3_ENDPOINT: ${S3_ENDPOINT_2}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID_2}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY_2}
      S3_BUCKET: ${S3_BUCKET_2}
      S3_PREFIX: ${S3_PREFIX_2}
      S3_REGION: ${S3_REGION_2}
    networks:
      - internal-network


networks:
  internal-network:
  postgres-network:
    external: true
